#file=open('sample.txt','w')
#data='''
#1.sravani
#2.sravs
#3.reva
#4.suppi
#5.nadhu
#6.gee
#7.puppy
#'''
#file.write(data)
#file.close()
#file=open('sample.txt','a')
#data='\n8.nani'
#file.write(data)
#file.close()
file=open(r"C:\Users\administrator.MCA\Desktop\content.txt.txt",'r',)
data=file.read()
print(data)
file.close()
